### ISSUE TITLE
Exception is raised when called without a subcommand

### ISSUE THREAD

**Issue by avylove** [microsoft/Linux-CommA#15]
This should not throw an exception. Probably it should print usage.

```
$ comma
Welcome to Commit Analyzer!
Traceback (most recent call last):
  File ".venv/bin/comma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "comma/__main__.py", line 242, in main
    args.func(args)
    ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by avylove** [comment]
Completed in #67
