### ISSUE TITLE
print-symbols raises an error if called twice without deleting repo

### ISSUE THREAD

**Issue by avylove** [microsoft/Linux-CommA#23]
The symbols subcommand currently fails with a raised exception when called more than once without deleting the database. It likely is trying to update the repo in an unsupported way.

```
$ comma --dry-run --no-fetch --verbose print-symbols --file /tmp/CommA_kaefc2on
Welcome to Commit Analyzer!
Starting the Symbol Checker...
05-18 13:24 root  INFO    Using local SQLite database at 'comma.db'.
05-18 13:24 root  INFO    Pulling 'linux-sym' repo...
Traceback (most recent call last):
  File "/bin/comma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lib/python3.11/site-packages/comma/__main__.py", line 242, in main
    args.func(args)
  File "/lib/python3.11/site-packages/comma/__main__.py", line 138, in <lambda>
    symbol_parser.set_defaults(func=(lambda args: print_missing_symbols(args.file)))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/comma/util/symbols.py", line 113, in print_missing_symbols
    get_hyperv_patch_symbols()
  File "/lib/python3.11/site-packages/comma/util/symbols.py", line 83, in get_hyperv_patch_symbols
    map_symbols_to_patch(
  File "/lib/python3.11/site-packages/comma/util/symbols.py", line 51, in map_symbols_to_patch
    repo = get_repo(name="linux-sym", shallow=False, pull=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/comma/util/tracking.py", line 59, in get_repo
    repo.remotes.origin.pull(progress=GitProgressPrinter())
  File "/lib/python3.11/site-packages/git/remote.py", line 1055, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/lib/python3.11/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v --progress -- origin
```

**Comment by avylove** [comment]
Fixed in #59
